<a href="https://colab.research.google.com/github/leejunho12316/NLP-study/blob/main/%EC%9E%90%EC%97%B0%EC%96%B4%EC%B2%98%EB%A6%AC_4%EC%A3%BC%EC%B0%A8_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 텍스트로 단어집합을 생성

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
t = Tokenizer()
text = "Your Dad is fucking great. Your Mom is fucking Dad."
t.fit_on_texts([text])

print("단어집합 : ", t.word_index)

단어집합 :  {'your': 1, 'dad': 2, 'is': 3, 'fucking': 4, 'great': 5, 'mom': 6}


# 단어집합으로 텍스트를 시퀀스로 변환하기

In [ ]:
seq = t.texts_to_sequences([text])
print("시퀀스 변환 :", seq)

시퀀스 변환 : [[1, 2, 3, 4, 5, 1, 6, 3, 4, 2]]


# 패딩

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

x = pad_sequences([[2],[6,7,10,7,88],[2,4]], maxlen = 5, padding = 'pre')
print(x)

[[ 0  0  0  0  2]
 [ 6  7 10  7 88]
 [ 0  0  0  2  4]]


In [ ]:
pad = pad_sequences(seq, maxlen = 100, padding='pre')
pad

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 2, 3, 4, 5, 1, 6, 3, 4, 2]], dtype=int32)

# Embedding 레이어

1.   텍스트 데이터 어휘 크기
2.   단어가 표현되는 벡터 공간의 크기
3.   입력 시퀀스의 길이




In [ ]:
import numpy as np
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential

model = Sequential()
model.add(Embedding(100, 4, input_length = 3))

In [ ]:
input_array = np.random.randint(100, size=(32,3))
model.compile('rmsprop', 'mse')
output_array = model.predict(input_array)
print(output_array.shape)

1/1 [==============================] - 0s 109ms/step
(32, 3, 4)




---

# 예제 : 스팸 메일 분류하기

In [28]:
import numpy as np
from tensorflow.keras.layers import Embedding, Flatten, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

docs = [	'additional income',
		'best price',
		'big bucks',
		'cash bonus',
		'earn extra cash',
		'spring savings certificate',
		'valero gas marketing',
		'all domestic employees',
		'nominations for oct',
		'confirmation from spinner']

labels = np.array([1,1,1,1,1,0,0,0,0,0])

vocab_size = 50
#one_hot 인코딩같이 one_hot 벡터 (0,0,0,1)이런거 만드는게 아님. 벡터 인덱스 반환.
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[36, 2], [46, 48], [17, 30], [35, 17], [14, 24, 35], [48, 23, 8], [1, 43, 19], [41, 48, 36], [28, 34, 15], [24, 21, 9]]


In [29]:
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[36  2  0  0]
 [46 48  0  0]
 [17 30  0  0]
 [35 17  0  0]
 [14 24 35  0]
 [48 23  8  0]
 [ 1 43 19  0]
 [41 48 36  0]
 [28 34 15  0]
 [24 21  9  0]]


In [30]:
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length = max_length)) #인수 숫자 왜 저렇게 넣어
model.add(Flatten()) #Flatten?
model.add(Dense(1, activation = 'sigmoid')) #sigmoid는 1차원 밖에 입력이 안되

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_docs, labels, epochs=50, verbose=0)

loss, accuracy = model.evaluate(padded_docs,labels,verbose=0)
print(accuracy)

1.0


In [32]:
test = ['big income']
encoded_test = [one_hot(d,vocab_size) for d in test]
padded_test = pad_sequences(encoded_test, maxlen=max_length, padding='post')

print(model.predict(padding_test))

NameError: name 'padding_test' is not defined

# 두 번째

In [65]:
import numpy as np
from tensorflow.keras.layers import Embedding, Flatten, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

text_data="""Soft as the voice of an angel\n
Breathing a lesson unhead\n
Hope with a gentle persuasion\n
Whispers her comforting word\n
Wait till the darkness is over\n
Wait till the tempest is done\n
Hope for sunshine tomorrow\n
After the shower
"""


In [66]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text_data])

encoded = tokenizer.texts_to_sequences([text_data])[0]
print("인코딩된 text :", encoded)

print()
print(tokenizer.word_index)
vocab_size = len(tokenizer.word_index)
print("어휘 크기 : ",vocab_size+1)

인코딩된 text : [7, 8, 1, 9, 10, 11, 12, 13, 2, 14, 15, 3, 16, 2, 17, 18, 19, 20, 21, 22, 4, 5, 1, 23, 6, 24, 4, 5, 1, 25, 6, 26, 3, 27, 28, 29, 30, 1, 31]

{'the': 1, 'a': 2, 'hope': 3, 'wait': 4, 'till': 5, 'is': 6, 'soft': 7, 'as': 8, 'voice': 9, 'of': 10, 'an': 11, 'angel': 12, 'breathing': 13, 'lesson': 14, 'unhead': 15, 'with': 16, 'gentle': 17, 'persuasion': 18, 'whispers': 19, 'her': 20, 'comforting': 21, 'word': 22, 'darkness': 23, 'over': 24, 'tempest': 25, 'done': 26, 'for': 27, 'sunshine': 28, 'tomorrow': 29, 'after': 30, 'shower': 31}
어휘 크기 :  32


In [67]:
sequences = list()
for i in range(1, len(encoded)):
  sequence = encoded[i-1:i+1]
  #print(f"encoded[{i-1}:{i+1}] : {encoded[i-1:i+1]}")
  sequences.append(sequence)

print(sequences)

[[7, 8], [8, 1], [1, 9], [9, 10], [10, 11], [11, 12], [12, 13], [13, 2], [2, 14], [14, 15], [15, 3], [3, 16], [16, 2], [2, 17], [17, 18], [18, 19], [19, 20], [20, 21], [21, 22], [22, 4], [4, 5], [5, 1], [1, 23], [23, 6], [6, 24], [24, 4], [4, 5], [5, 1], [1, 25], [25, 6], [6, 26], [26, 3], [3, 27], [27, 28], [28, 29], [29, 30], [30, 1], [1, 31]]


In [68]:
sequences = np.array(sequences)
X, y = sequences[:,0], sequences[:,-1]

print("X = ",X)
print("y = ",y)

X =  [ 7  8  1  9 10 11 12 13  2 14 15  3 16  2 17 18 19 20 21 22  4  5  1 23
  6 24  4  5  1 25  6 26  3 27 28 29 30  1]
y =  [ 8  1  9 10 11 12 13  2 14 15  3 16  2 17 18 19 20 21 22  4  5  1 23  6
 24  4  5  1 25  6 26  3 27 28 29 30  1 31]


In [69]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN, LSTM

model = Sequential()
model.add(Embedding(vocab_size, 10, input_length = 1))
model.add(LSTM(50))
model.add(Dense(vocab_size, activation='softmax'))

In [70]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=500, verbose=2)

Epoch 1/500


InvalidArgumentError: Graph execution error:

Detected at node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits defined at (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main

  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code

  File "/usr/local/lib/python3.10/dist-packages/colab_kernel_launcher.py", line 37, in <module>

  File "/usr/local/lib/python3.10/dist-packages/traitlets/config/application.py", line 992, in launch_instance

  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelapp.py", line 619, in start

  File "/usr/local/lib/python3.10/dist-packages/tornado/platform/asyncio.py", line 195, in start

  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever

  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once

  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run

  File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 685, in <lambda>

  File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 738, in _run_callback

  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 825, in inner

  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 786, in run

  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 361, in process_one

  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper

  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 261, in dispatch_shell

  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper

  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 539, in execute_request

  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper

  File "/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py", line 302, in do_execute

  File "/usr/local/lib/python3.10/dist-packages/ipykernel/zmqshell.py", line 539, in run_cell

  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell

  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell

  File "/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner

  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async

  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes

  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code

  File "<ipython-input-70-925986d7bb16>", line 2, in <cell line: 2>

  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1807, in fit

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1401, in train_function

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1384, in step_function

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1373, in run_step

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1151, in train_step

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1209, in compute_loss

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/compile_utils.py", line 277, in __call__

  File "/usr/local/lib/python3.10/dist-packages/keras/src/losses.py", line 143, in __call__

  File "/usr/local/lib/python3.10/dist-packages/keras/src/losses.py", line 270, in call

  File "/usr/local/lib/python3.10/dist-packages/keras/src/losses.py", line 2454, in sparse_categorical_crossentropy

  File "/usr/local/lib/python3.10/dist-packages/keras/src/backend.py", line 5775, in sparse_categorical_crossentropy

Received a label value of 31 which is outside the valid range of [0, 31).  Label values: 17 5 11 30 28 14 25 31 20 6 19 13 27 6 2 10 15 1 21 24 9 4 23 3 29 18 2 1 3 5 12 26
	 [[{{node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_train_function_16215]

세 번째